export const ERROR_CODES = {
  GREENHOUSE_NOT_FOUND: 'GREENHOUSE_NOT_FOUND',
  SENSOR_NOT_FOUND: 'SENSOR_NOT_FOUND',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_HANDOVER: 'INVALID_HANDOVER',
  HANDOVER_TIME_CONFLICT: 'HANDOVER_TIME_CONFLICT',
} as const;
