export const ERROR_CODES = {
  GREENHOUSE_NOT_FOUND: 'GREENHOUSE_NOT_FOUND',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  ZONE_GREENHOUSE_MISMATCH: 'ZONE_GREENHOUSE_MISMATCH',
  SENSOR_NOT_FOUND: 'SENSOR_NOT_FOUND',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INVALID_HANDOVER_TIME: 'INVALID_HANDOVER_TIME',
  HANDOVER_TIME_CONFLICT: 'HANDOVER_TIME_CONFLICT',
  HANDOVER_REASON_REQUIRED: 'HANDOVER_REASON_REQUIRED',
} as const;

export const ERROR_MESSAGES = {
  SENSOR_NOT_FOUND: '传感器不存在',
  GREENHOUSE_NOT_FOUND: '目标温室不存在',
  ZONE_NOT_FOUND: '目标区域不存在',
  ZONE_GREENHOUSE_MISMATCH: '所选区域不属于目标温室',
  HANDOVER_TIME_CONFLICT: '交接时间必须晚于该传感器上一次交接时间，请调整后重试',
  INVALID_HANDOVER_TIME: '交接时间格式不正确，应为 YYYY-MM-DD HH:mm',
  HANDOVER_REASON_REQUIRED: '重复提交或交接必须填写原因说明',
} as const;
